spring:
  application:
    name: eventbridge
  datasource:
    url: jdbc:h2:mem:eventbridgedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      default-receive-queue: eventbridge-queue

server:
  port: 8080

logging:
  level:
    com.eventbridge: DEBUG
    org.springframework.amqp: DEBUG